# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)
b <- board_folder(path = "/var/folders/pn/9hhpnpd15_d2k3qp5k814nnh0000gq/T/Rtmpfya9ml/pins-b0de129de86")
v <- vetiver_pin_read(b, "gam_tds9")

#* @plumber
function(pr) {
    pr %>% vetiver_api(v)
}
